@startuml

start
fork
  : Create Inspection;
  Group Hub
    :Hub : User Creates a Inspection;
    :Hub : Create Create Message;    
  EndGroup
  
  Group Service Bus
    :Bus : Pass Service Request;
  EndGroup  

  Group Service
    :SVC : Create Inspection Object in Datastore;
    :SVC : Send Inspection to ACT;
    :SVC : Update Inspection Object in Datastore;
  EndGroup

fork again
  : Update Inspection;
  Group Hub
    :Hub : User Updates a Inspection;   
    :Hub : Create Update Message;        
  EndGroup
  
  Group Service Bus
    :Bus : Pass Service Request;
  EndGroup  

  Group Service
    :SVC : Update Inspection Object in Datastore;
    :SVC : Send Inspection to ACT;
    :SVC : Update Inspection Object in Datastore;
  EndGroup  

fork again
  : Delete Inspection;
  Group Hub
    :Hub : Inspection reaches End;
    :Hub : Create Delete Message;
  EndGroup
  
  Group Service Bus
    :Bus : Pass Service Request;
  EndGroup  

  Group Service
    :SVC : Update Inspection Object in Datastore;
    :SVC : Delete Inspection on ACT;
    :SVC : Delete Inspection Object in Datastore;
  EndGroup  
fork again
  : Report ready;  
  Group Service
    :SVC : Webhook received;
    :SVC : Get Report from ACT;
    :SVC : Store Report in Doc Manager;
    :SVC : Publish Message to HUB;
  Endgroup  

  Group Service Bus
    :Bus : Pass Service Response;
  EndGroup    

  Group Hub
    :Hub : Subscribe to Response Bus;
    :Hub : Save Report Doc Manager ID in Attachment table;
    :Hub : Notify User;
  EndGroup
fork again 
  : Get Tenancies;
  Group Hub
    :Hub : Periodic housekeeping task;
    :Hub : Create Housekeeping Message;
  EndGroup  

  Group Service Bus
    :Bus :Pass Service Request;
  EndGroup 

  Group Service
    :SVC : Get Tenancies from ACT;
    :SVC : Process Array, and Update Inspection Objects in Datastore;
    :SVC : Publish Message to HUB;
  Endgroup   

  Group Service Bus
    :Bus : Pass Service Response;
  EndGroup   

  Group Hub
    :Hub : Subscribe to Response Bus;
    :Hub : Process Array of Tenancies;
    :Hub : Update Next Report Date on Inspection;
  EndGroup    
endfork


stop

@enduml
